# Generated by Django 4.2.2 on 2023-07-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALAXIA', 'Galaxia'), ('BURACO NEGRO', 'Burado Negro'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
